### ISSUE TITLE
`More blocks deallocated than allocated` message on application close

### ISSUE THREAD

**Issue by OfficialURL** [zakarumych/gpu-alloc#49]
I ran a `cargo update` a few minutes ago, and now every time my application closes, it prints out this message on the command line. It wasn't doing this previously, and since this is quite a deep dependency in my project, I don't really know how to fix or disable it.

**Comment by zakarumych** [comment]
This is new error message, added in recent patch version, intended to be a hint if some subtle bug with deallocating more blocks than there were allocated. Probably because some blocks belongs to different instance of `GpuAllocator`.
I guess it is fired erroneously as `wgpu` uses single `GpuAllocator` instance.

**Comment by zakarumych** [comment]
Should be fixed now. Just run `cargo update` again
